USE e_commerce_analytics;

-- 1. Find the top 10 customers based on total spending.
WITH spending AS(
	SELECT c.customer_id,c.name,
    ROUND(SUM(oi.quantity*oi.unit_price*(1-oi.discount/100)),2) AS total_spending
    FROM customers c
    JOIN orders o
    ON c.customer_id=o.customer_id 
    JOIN order_items oi
    ON o.order_id=oi.order_id
    GROUP BY c.customer_id,c.name
),customer_rank AS(
	SELECT *,
    RANK() OVER(
		ORDER BY total_spending DESC
        ) AS top_customers
        FROM spending
        )
	SELECT *FROM customer_rank
    WHERE top_customers <=10;
    
-- 2. Customers whose total spending is greater than the average spending of all customers.
WITH spending AS(
	SELECT c.customer_id,c.name,
    ROUND(SUM(oi.quantity*oi.unit_price*(1-oi.discount/100)),2) AS total_spending
    FROM customers c
    JOIN orders o
    ON c.customer_id=o.customer_id 
    JOIN order_items oi
    ON o.order_id=oi.order_id
    GROUP BY c.customer_id,c.name
    ), average_spending AS(
    SELECT *,
    ROUND(AVG(total_spending) OVER(),2) AS avg_spending
    FROM spending
    ) SELECT * FROM average_spending
    WHERE total_spending>avg_spending;
    
-- 3. Find customers who placed 3 or more orders.
SELECT 
    c.customer_id,
    c.name,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name
HAVING COUNT(o.order_id) >= 3;

-- 4. Find the total revenue generated by each customer segment.
SELECT c.customer_segment,
ROUND(SUM(oi.quantity*oi.unit_price*(1-discount/100)),2)AS total_revenue
FROM customers c 
JOIN orders o
ON c.customer_id=o.customer_id
JOIN order_items oi
ON o.order_id=oi.order_id
GROUP BY c.customer_segment;
    
-- 5. Find the total revenue generated from each shipping city.
SELECT o.shipping_city,
ROUND(SUM(oi.quantity*oi.unit_price*(1-discount/100)),2) AS total_revenue
FROM orders o
JOIN order_items oi
ON o.order_id=oi.order_id
GROUP BY o.shipping_city
ORDER BY total_revenue DESC;

-- 6. Find the total revenue for each month.
SELECT MONTH(o.order_date) AS month_number,
MONTHNAME(o.order_date) AS month_name,
ROUND(SUM(oi.quantity*oi.unit_price*(1-discount/100)),2) AS total_revenue
FROM orders o
JOIN order_items oi
ON o.order_id=oi.order_id
WHERE YEAR(o.order_date)=2025
GROUP BY MONTH(o.order_date),MONTHNAME(o.order_date)
ORDER BY MONTH(o.order_date);

-- 7. Find the total revenue generated by each product category.
SELECT p.category,
ROUND(
	SUM(oi.quantity*oi.unit_price*(1-discount/100)),
    2) AS total_revenue
FROM products p
JOIN order_items oi 
ON p.product_id=oi.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;

-- 8. Find the total revenue generated through each sales channel.
SELECT o.sales_channel,
ROUND(
	SUM(oi.quantity*oi.unit_price*(1-discount/100)),
    2) AS total_revenue
FROM orders o
JOIN order_items oi 
ON o.order_id=oi.order_id
GROUP BY o.sales_channel
ORDER BY total_revenue DESC;

-- 9. Find the top 10 products generating the highest total revenue.
SELECT p.product_id,p.product_name,
ROUND(
	SUM(oi.quantity*oi.unit_price*(1-discount/100)),
    2) AS total_revenue
FROM products p 
JOIN order_items oi
ON p.product_id=oi.product_id
GROUP BY p.product_id,p.product_name
ORDER BY total_revenue DESC
LIMIT 10;

-- 10. Find the top 5 customers who have placed the highest number of orders.
SELECT c.customer_id,c.name,
COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
ON c.customer_id=o.customer_id
GROUP BY c.customer_id,c.name
ORDER BY total_orders DESC
LIMIT 5;

-- 11. Find the total revenue for each combination of product category and sales channel.
SELECT p.category,o.sales_channel,
ROUND(
	SUM(oi.quantity*oi.unit_price*(1-discount/100)),
    2) AS total_revenue
FROM products p
JOIN order_items oi
ON p.product_id=oi.product_id
JOIN orders o
ON oi.order_id=o.order_id
GROUP BY p.category,o.sales_channel
ORDER BY total_revenue DESC;

-- 12. Find the average order value (AOV) for each sales channel
WITH order_value AS(
	SELECT o.sales_channel,o.order_id,ROUND(
		SUM(oi.quantity*oi.unit_price*(1-discount/100)),
		2) AS ord_value
	FROM orders o 
	JOIN order_items oi
	ON o.order_id=oi.order_id
	GROUP BY o.order_id
    ),
average_value AS(
	SELECT sales_channel,AVG(ord_value)AS avg_order_value
    FROM order_value
    GROUP BY sales_channel
    ) SELECT *FROM average_value
    ORDER BY avg_order_value DESC;
    
-- 13. Find the total revenue generated from each customer city.
SELECT c.city,
ROUND(
		SUM(oi.quantity*oi.unit_price*(1-discount/100)),
		2) AS total_revenue
	FROM customers c
    JOIN orders o
    ON c.customer_id=o.customer_id
    JOIN order_items oi
    ON o.order_id=oi.order_id
    GROUP BY c.city
    ORDER BY total_revenue DESC;
    
-- 14. Find the number of orders placed in each month of 2025.
SELECT MONTH(order_date) AS month_number,
MONTHNAME(order_date) AS month_name,
COUNT(order_id) AS total_orders
FROM orders 
WHERE YEAR(order_date)=2025
GROUP BY MONTH(order_date),MONTHNAME(order_date)
ORDER BY month_number;

-- 15 . Find the top 10 customers by total revenue.
SELECT c.customer_id,c.name,
ROUND(
	SUM(oi.quantity*oi.unit_price*(1-discount/100)),
	2) AS total_revenue
	FROM customers c
    JOIN orders o
    ON c.customer_id=o.customer_id
    JOIN order_items oi
    ON o.order_id=oi.order_id
    GROUP BY c.customer_id,c.name
    ORDER BY total_revenue DESC
    LIMIT 10;

-- 16. Find the total revenue generated for each order status.
SELECT o.order_status,
ROUND(
	SUM(oi.quantity*oi.unit_price*(1-discount/100)),
	2) AS total_revenue
    FROM orders o
    JOIN order_items oi
    ON o.order_id=oi.order_id
    GROUP BY o.order_status
    ORDER BY total_revenue DESC;
    
-- 17. Find the average product rating for each product category.
SELECT p.category,ROUND(AVG(r.rating),2) AS avg_rating
FROM products p
JOIN reviews r
ON p.product_id=r.product_id
GROUP BY p.category
ORDER BY avg_rating DESC;

-- 18. Find the total revenue for each combination of customer segment and sales channel
SELECT c.customer_segment,o.sales_channel,
ROUND(
	SUM(oi.quantity*oi.unit_price*(1-discount/100)),
	2) AS total_revenue
    FROM customers c
    JOIN orders o
    ON c.customer_id=o.customer_id
    JOIN order_items oi
    ON o.order_id=oi.order_id
    GROUP BY c.customer_segment,o.sales_channel
    ORDER BY total_revenue DESC;
    
-- 19. Find the top 5 product categories based on total units sold.
SELECT p.category,SUM(oi.quantity)AS total_units_sold
FROM products p
JOIN order_items oi
ON p.product_id=oi.product_id
GROUP BY p.category
ORDER BY total_units_sold DESC
LIMIT 5;

-- 20. Find the payment success rate for each payment mode.
WITH payment AS(
	SELECT payment_mode,
	COUNT(payment_id) AS total_payments,
	SUM(CASE WHEN payment_status='Successful' THEN 1 ELSE 0 END)AS successfull_payments
    FROM payments
    GROUP BY payment_mode
    )SELECT *,ROUND((successfull_payments/total_payments)*100,2) AS success_rate
    FROM payment
    ORDER BY success_rate DESC;
    
SELECT *FROM payments;
    

